### PR TITLE
Microsite updates && replacing tut to mdoc

### PR DESCRIPTION
**Pull request by SunPj**

### CODE REVIEW

**Comment by pidge** [comment]
@SunPj Looks like there's still an implicit dependency on `tut` in there somewhere
```
➜  spark-alchemy git:(495abf2) ✗ sbt "project docs" makeMicrosite
[info] welcome to sbt 1.3.12 (Amazon.com Inc. Java 1.8.0_275)
[info] loading global plugins from /Users/peter/.sbt/1.0/plugins
[info] loading settings for project spark-alchemy-build from plugins.sbt ...
[info] loading project definition from /Users/peter/d/spark-alchemy/project
[info] loading settings for project alchemy from build.sbt ...
[info] set current project to spark-alchemy (in build file:/Users/peter/d/spark-alchemy/)
[info] set current project to spark-alchemy-docs (in build file:/Users/peter/d/spark-alchemy/)
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[warn] Credentials file /Users/peter/.sbt/sonatype_credentials does not exist
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.tpolecat:tut-core_2.12:0.6.13
[error]   Not found
[error]   Not found
[error]   not found: /Users/peter/.ivy2/local/org.tpolecat/tut-core_2.12/0.6.13/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom) while downloading https://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.tpolecat:tut-core_2.12:0.6.13
[error]   Not found
[error]   Not found
[error]   not found: /Users/peter/.ivy2/local/org.tpolecat/tut-core_2.12/0.6.13/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom (Server returned HTTP response code: 403 for URL: https://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom) while downloading https://dl.bintray.com/tpolecat/maven/org/tpolecat/tut-core_2.12/0.6.13/tut-core_2.12-0.6.13.pom
[error] Total time: 3 s, completed Jul 12, 2021 1:47:59 PM
```

**Comment by SunPj** [comment]
@pidge The microsite sbt plugin we use, depends on both tut and mdoc and gives user a choice to use either. But everything compiles on my machine. Let me try to clean my local cache and check the build one more time

**Comment by SunPj** [comment]
@pidge I removed my local .m2 and .ivy2 caches and it still compiled. I updated microsite version and there shouldn't be any tut dependency. It looks they don't support it anymore https://github.com/47degrees/sbt-microsites/pull/527

Could you please check whether everything is working now? Thanks

**Review by pidge — APPROVED** [review]
That did it, thanks!

**Pull request merged**
