### PR TITLE
Spark 3.1.2 support

### PR DESCRIPTION
**Pull request by j03wang**
- Addresses issue #21.
- Ran/passes all tests, but didn't run the postgres interop tests.

### CODE REVIEW

**Comment by ssimeonov** [comment]
Please update `VERSION` according to https://github.com/swoop-inc/spark-alchemy/blob/master/DEVELOPMENT.md#project-version-numbers

**Comment by j03wang** [comment]
> Please update `VERSION` according to https://github.com/swoop-inc/spark-alchemy/blob/master/DEVELOPMENT.md#project-version-numbers

I'm assuming this would be 2.0.0, since we've changed dependency versions?

**Comment by ssimeonov** [comment]
`1.1.0` makes sense because there are no incompatible API changes, but the change is not a bug fix. https://semver.org/#summary

**Review by pidge — APPROVED** [review]
This looks good & passes Postgres integration tests. `master` is currently broken thanks to the `tut` plugin being abandoned, so for now will hold off merging til that's fixed and we can cut a release.

**Pull request merged**
